### ISSUE TITLE
not works

### ISSUE THREAD

**Issue by CommanderTvis** [ConnorLinfoot/ActionBarAPI#13]
hi, i'm trying to use your plugin to make dynamic players' HP updates. when i create simplest event on players join, your mod returns exception. why? 

[My listener](https://gist.github.com/CommanderTvis/868f16501a94ecab42d87c7fa0a3dc22)

[My log](https://gist.github.com/CommanderTvis/4747afcd7974c3786196447a64c880a1)

**Comment by ConnorLinfoot** [comment]
Seems to work fine for myself, can you try again using the latest Spigot 1.13.1 build?

**Comment by CommanderTvis** [comment]
I used exactly latest build

**Comment by ConnorLinfoot** [comment]
I'm afraid I'm not sure what your issue is then :/

**Comment by ConnorLinfoot** [comment]
It could be something with Kotlin causing the issue. Personally, I avoid that so I wouldn't know.

**Comment by CommanderTvis** [comment]
Ok, i'll try your API with only Java. By the wat, now I use TextAPI, it works well with Kotlin
