### ISSUE TITLE
What do I need to insert as a player? 

### ISSUE THREAD

**Issue by minefred-real** [ConnorLinfoot/ActionBarAPI#31]
![image](https://user-images.githubusercontent.com/59933333/102713105-09c81f00-42c6-11eb-806a-a4d87630785b.png)

What do I need to insert as a player? commandsender.getPlayer() does not work...

**Comment by ConnorLinfoot** [comment]
It does take a Bukkit entity player - https://github.com/ConnorLinfoot/ActionBarAPI/blob/master/src/main/java/com/connorlinfoot/actionbarapi/ActionBarAPI.java#L43
