### ISSUE TITLE
Ticket 8

### ISSUE THREAD

**Issue by Rocologo** [ConnorLinfoot/ActionBarAPI#9]
Hi  again

I have some more investigation on ticket https://github.com/ConnorLinfoot/ActionBarAPI/issues/8

Version 1.5.0 and version 1.5.1 starts fine on my server. So I think you must have made a change in V1.5.2, which is the root cause?

**Comment by ConnorLinfoot** [comment]
Nothing was changed in 1.5.2 that should affect anything apart from the updater - https://github.com/ConnorLinfoot/ActionBarAPI/commit/e6e6ea2037f462c133e2252e7cd8de9b01964e9d

**Comment by Rocologo** [comment]
Well the change was big enough... v1.5.1 works, v1.5.2 does not

**Comment by ConnorLinfoot** [comment]
1.5.2 works fine for myself and many others, you're the only person to report the issue.

**Comment by ConnorLinfoot** [comment]
There's literally nothing I can do, I've tested it on multiple versions on multiple servers and had no issues. The 1.5.2 update changes nothing other than the updater so nothing can be a "big enough" change to cause issues.

Sorry I would fix it but I can't fix something I can't replicate.
